services:
  - type: web
    name: pdf-quiz-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: RENDER
        value: true
